import { CARS, PARTS, TRACKS, DIFFICULTIES } from './data.js';
import { buildCar, idealShift, clamp } from './physics.js';
import { newCar, loadSave } from './storage.js';
import { raceHUD, escape } from './views.js';
import { drawTrack } from './graphics.js';
import { EngineAudio } from './audio.js';
import { installSpritePack, componentOptions, getCarSprite } from './car-assets.js';
import { demoSpritePack } from './demo-sprite-pack.js';
import { createDriveLab, startDriving, stageDriveLab, launchDriveLab, shiftDriveLab, setLabSpeed, stepDriveLab, labTelemetry } from './drive-lab-model.js';
import { telemetryCSV } from './drive-lab-csv.js';

const $=id=>document.getElementById(id),esc=escape;
let owned=newCar(CARS[0].id),lab=createDriveLab(buildCar(owned)),pack={schemaVersion:1,cars:{}},records=[],events=[],sampleClock=0,sampleAccumulator=0,lastFrame=0,accumulator=0,lastFeedback='',sound=false;
const keyboard=new Set(),pointers=new Map(),audio=new EngineAudio();
const select=(label,id,entries,value='')=>`<label class="field"><span>${esc(label)}</span><select id="${id}" aria-label="${esc(label)}">${entries.map(e=>{const [v,l]=Array.isArray(e)?e:[e,e];return `<option value="${esc(v)}" ${String(value)===String(v)?'selected':''}>${esc(l)}</option>`;}).join('')}</select></label>`;
const range=(label,id,min,max,step,value)=>`<label class="field"><span>${esc(label)} <output id="${id}-value">${value}</output></span><input id="${id}" aria-label="${esc(label)}" type="range" min="${min}" max="${max}" step="${step}" value="${value}"></label>`;
const number=(label,id,min,max,step,value)=>`<label class="field"><span>${esc(label)}</span><input id="${id}" aria-label="${esc(label)}" type="number" min="${min}" max="${max}" step="${step}" value="${value}"></label>`;
const toggle=(label,id,checked=false)=>`<label>${esc(label)}<input id="${id}" type="checkbox" ${checked?'checked':''} aria-label="${esc(label)}"></label>`;
const button=(label,id,kind='secondary')=>`<button id="${id}" class="button ${kind}" type="button">${label}</button>`;
const metric=(label,id)=>`<div class="lab-metric"><span>${label}</span><strong id="${id}">—</strong></div>`;
function dial(id,title,max,unit){
  return `<svg class="lab-dial" viewBox="0 0 240 230" role="img" aria-label="${title} gauge"><circle cx="120" cy="120" r="100" fill="#11151d" stroke="#333b48" stroke-width="2"/><path d="M45 181A96 96 0 1 1 195 181" fill="none" stroke="#f5814c" opacity=".5" stroke-width="4"/>${Array.from({length:11},(_,i)=>{const angle=-130+i*26,rad=angle*Math.PI/180;return `<g transform="translate(120 120) rotate(${angle})"><path d="M0 -84V-95" stroke="${i>8?'#ff885b':'#8b97a8'}" stroke-width="2"/></g><text x="${120+Math.sin(rad)*72}" y="${124-Math.cos(rad)*72}" text-anchor="middle" font-size="9">${Math.round(max*i/10*10)/10}</text>`;}).join('')}<g id="${id}-needle" transform="rotate(-130 120 120)"><path d="M116 135L120 42L124 135Z" fill="#ff8455"/><circle cx="120" cy="120" r="8" fill="#dfd2c4"/></g><text x="120" y="166" text-anchor="middle" class="dial-title">${title}</text><text id="${id}-value" x="120" y="194" text-anchor="middle" class="dial-value">0</text><text x="120" y="215" text-anchor="middle" font-size="8">${unit}</text></svg>`;
}
function shell(){
  $('drive-lab').innerHTML=`<div class="lab-links"><a href="./index.html">← Garage</a><a href="./asset-preview.html">Car asset preview</a></div><header class="lab-header"><div><span class="eyebrow">REDLINE / TEST DRIVE LAB</span><h1>Every input. Every detail.</h1><p>Drive continuously, practice the lights, or inspect a car at idle. No opponent, entry fee, or finish line.</p></div><span class="tag">ISOLATED SESSION</span></header>
  <div class="lab-grid"><section class="lab-stage"><div class="lab-toolbar">${button('Start driving','start','primary')}${button('Stage & start tree','stage')}${button('Burnout','burnout')}${button('Pause','pause')}${button('Step · 1/120 s','step')}${button('Reset session','reset')}</div><section class="track-container"><canvas id="track-canvas" aria-label="Test drive with animated car wheels and brakes"></canvas><div class="tree"><div class="tree-stage" id="lab-prestage"><i></i><i></i></div><div class="tree-stage" id="lab-stage-light"><i></i><i></i></div><div class="tree-lights"><i data-light="1"></i><i data-light="2"></i><i data-light="3"></i><i data-light="green"></i><i data-light="red"></i></div></div><div class="lab-scene-status" id="phase-status">IDLE</div><div class="track-label" id="track-label">HARBOR RUN</div></section><div id="shared-hud">${raceHUD(lab.vehicle.car)}</div><div class="lab-dials" id="lab-dials"></div>
  <div class="lab-pedals"><button class="pedal" data-pedal="throttle"><kbd>W</kbd> Throttle</button><button class="pedal" data-pedal="clutch"><kbd>C</kbd> Clutch</button><button class="pedal" data-pedal="brake"><kbd>S</kbd> Brake</button></div><div class="lab-shifts">${button('<kbd>Q</kbd> Shift down','shift-down')}${button('<kbd>Space</kbd> Launch','launch','primary')}${button('<kbd>E</kbd> Shift up','shift-up')}</div><div class="lab-actions-row">${button('<kbd>N</kbd> Neutral','neutral')}${button('<kbd>R</kbd> Rev blip','blip')}</div><p class="race-help">W / ↑ THROTTLE · C CLUTCH · S / ↓ BRAKE · E / → UP · Q / ← DOWN · SPACE LAUNCH · N NEUTRAL · R BLIP · ESC PAUSE</p><div class="lab-feedback" id="lab-feedback" role="status"></div></section>
  <aside class="lab-side"><section class="panel"><h2>Driver controls</h2><div class="lab-control-grid">${select('Transmission','transmission',[['auto','Automatic'],['manual','Manual sequential'],['clutch','Manual + clutch']],'manual')}${select('Launch control','launch-control',[['auto','Automatic'],['assisted','Assisted'],['manual','Manual']],'manual')}${select('Staging','staging',[['auto','Automatic'],['manual','Manual pre-stage']],'auto')}${select('Difficulty preset','difficulty',Object.keys(DIFFICULTIES),'Normal')}${range('Throttle position','throttle-input',0,100,1,0)}${range('Clutch pedal','clutch-input',0,100,1,0)}${range('Brake pressure','brake-input',0,100,1,0)}${range('Traction assistance','traction',0,100,5,40)}${range('Simulation speed','time-scale',.25,2,.25,1)}</div><div class="lab-switches">${toggle('Latch full throttle','latch-throttle')}${toggle('Hold clutch down','latch-clutch')}${toggle('Automatic rev matching','rev-match',true)}${toggle('Engine sound','sound')}</div><p class="lab-note">Pedals support keyboard, mouse and multitouch. Sliders latch an exact pedal position. A pressed clutch disconnects the engine.</p></section>
  <section class="panel"><h2>Quick tests</h2><div class="lab-scenario-grid">${['Free rev','Auto pull','Clutch test','Brake test','Wet launch','Rolling test'].map((l,i)=>button(l,`scenario-${i}`)).join('')}</div><div class="lab-actions-row">${number('Set speed · km/h','prime-speed',0,400,1,80)}${button('Apply speed','apply-speed')}</div><p class="lab-note">Rolling tests seed a starting speed. Brake input uses a generic grip-limited stop for this lab.</p></section></aside></div>
  <div class="lab-bottom"><section class="panel"><div class="section-heading"><h2>Live telemetry</h2>${button('Export telemetry CSV','export-data')}</div><div class="lab-metrics">${[['DISTANCE','distance'],['REACTION','reaction'],['MAX SPEED','max-speed'],['ACCELERATION','accel'],['TORQUE','engine-torque'],['POWER','engine-power'],['TIRE TEMP','tire-temp'],['TIRE WEAR','tire-wear'],['SHIFT INTERRUPTION','shift-timer'],['THROTTLE','pedal-throttle'],['CLUTCH PEDAL','pedal-clutch'],['BRAKE','pedal-brake']].map(([l,id])=>metric(l,id)).join('')}</div><canvas class="lab-plot" id="telemetry-plot" aria-label="Last 60 seconds of speed engine RPM boost and wheel slip"></canvas><div class="lab-legend">${[['SPEED','#6bd8ee'],['RPM','#ff9061'],['BOOST','#bd9efa'],['SLIP','#ead175']].map(([l,color])=>`<span><i style="background:${color}"></i>${l}</span>`).join('')}</div><p class="lab-note">Plot: last 60 simulated seconds; each signal uses its own scale. CSV retains up to 10 minutes at 10 samples/second.</p></section>
  <section class="panel"><h2>Timing & feedback</h2><div class="lab-metrics">${[['60 FT','split-60ft'],['⅛ MILE','split-eighth'],['¼ MILE','split-quarter'],['½ MILE','split-half'],['1 MILE','split-mile'],['ENGINE STRESS','engine-stress']].map(([l,id])=>metric(l,id)).join('')}</div><ol class="lab-log" id="event-log" aria-label="Input and shift event log"></ol><div class="lab-actions-row">${button('Clear trace & log','clear-trace')}</div><p class="lab-note">Pass timing starts when the car launches; reaction is separate. Driving continues beyond every marker. Pause freezes physics; Step advances one fixed tick.</p></section></div>
  <details class="panel lab-tuner" open><summary>Car, conditions & tuning</summary><p id="lab-asset-status" class="lab-status">Loading local car layers…</p><p id="lab-error" class="lab-error" role="alert"></p><div class="lab-tune-columns"><div class="lab-tune-controls"><div class="lab-control-grid">${select('Vehicle','model',CARS.map(c=>[c.id,c.name]),owned.model)}${select('Artwork','artwork',[['factory','Model artwork'],['layer-demo','Layer geometry demo']],'factory')}${select('Track','track',TRACKS.map(t=>[t.id,t.name]),'dock')}${select('Weather','weather',['Dry','Wet'],'Dry')}${select('Time of day','day',['Night','Day'],'Night')}<label class="field"><span>Paint</span><input id="paint" aria-label="Paint" type="color" value="${owned.color}"></label>${select('Wheel component','wheel-component',[['','Factory']],'')}${select('Brake component','brake-component',[['','Factory']],'')}${select('Vector rim color','rim-color',['silver','black','bronze'],'silver')}${select('Paint finish','finish',['metallic','matte','pearl'],'metallic')}${range('Window tint','window-tint',0,.9,.05,.45)}${toggle('Club stripe','stripe')}${toggle('Rear spoiler','spoiler')}${range('Ride height','ride-height',-12,8,1,0)}${range('Mechanical condition','condition',25,100,1,100)}</div><div class="lab-actions-row">${button('Load selected garage build','garage-build')}${button('Restore factory build','factory-build')}</div><div id="car-info" class="lab-car-info"></div></div>
  <div><h2>Performance parts</h2><div class="lab-part-controls">${PARTS.map(p=>range(p.name,`part-${p.id}`,0,p.max,1,owned.upgrades[p.id] || 0)).join('')}</div></div>
  <div class="lab-tune-controls"><h2>Engine & gearing</h2>${number('Launch RPM','launch-rpm',900,15000,100,lab.vehicle.car.launchRPM)}${number('Shift target · 0 = optimal','shift-rpm',0,15000,100,0)}${number('Final drive','final-drive',2,5.5,.01,lab.vehicle.car.finalDrive)}${range('Tire pressure · PSI','pressure',16,40,1,30)}${range('Differential lock · %','diff',0,100,1,70)}${range('Boost setting · %','boost-setting',50,120,1,100)}<div class="lab-ratios" id="lab-ratios"></div><p class="lab-note">Tuning and upgrades reset the test vehicle. These changes stay in this session. Artwork selections change visuals only.</p></div></div></details><footer>REDLINE TEST DRIVE LAB · SHARED DRAG PHYSICS · NO GARAGE WRITES</footer>`;
  refreshCarUI();
}
function addEvent(message){events.unshift(`${sampleClock.toFixed(3)} s · ${message}`);events=events.slice(0,100);$('event-log').replaceChildren(...events.map(e=>{const li=document.createElement('li');li.textContent=e;return li;}));}
function options(id,entries){$(id).replaceChildren(...entries.map(([v,l])=>{const o=document.createElement('option');o.value=v;o.textContent=l;return o;}));}
function refreshCarUI({ratios=true}={}){
  const c=lab.vehicle.car;
  $('shared-hud').innerHTML=raceHUD(c,{neutral:c.gear===0});$('lab-dials').innerHTML=dial('speed-dial','SPEED',400,'KM/H')+dial('rpm-dial','ENGINE',Math.ceil((c.redline+500)/1000),'RPM × 1000')+dial('boost-dial','BOOST',3,'BAR');
  $('shift-rpm').previousElementSibling.textContent=c.transmissionType==='cvt'?'CVT power target · 0 = automatic':'Shift target · 0 = optimal';
  $('shift-rpm').setAttribute('aria-label',$('shift-rpm').previousElementSibling.textContent);
  for(const action of ['shift-up','shift-down'])$(action).disabled=c.transmissionType==='cvt';
  $('part-gearbox').disabled=c.transmissionType==='cvt';
  if(ratios)$('lab-ratios').innerHTML=c.transmissionType==='cvt'?`<p>CVT / continuous ${c.cvt.minRatio}-${c.cvt.maxRatio} modeled ratio range. No fixed gears.</p>`:c.ratios.map((r,i)=>number(`Gear ${i+1}`,`ratio-${i}`,.4,5.5,.01,r)).join('');
  $('car-info').textContent=`${c.name} · ${c.hp} HP · ${c.peakTorque} Nm · ${Math.round(c.mass)} kg · ${c.drive} · ${c.redline} RPM redline · ${c.transmissionType==='cvt'?'CVT':Math.round(c.shiftTime*1000)+' ms shifts'}`;
  const sprite=getCarSprite(c);for(const id of ['wheel-component','brake-component'])$(id).disabled=!sprite;
  $('paint').disabled=!!sprite&&!sprite.layers.paintMask;
  for(const id of ['rim-color','finish','window-tint','stripe','spoiler'])if($(id))$(id).disabled=!!sprite;
}
function readSettings(){return {transmission:$('transmission').value,launch:$('launch-control').value,staging:$('staging').value,traction:Number($('traction').value)/100,revMatch:$('rev-match').checked,surface:TRACKS.find(t=>t.id===$('track').value).surface,wet:$('weather').value==='Wet'};}
function resetSession({clearTrace=true,preserveInputs=false}={}){
  clearHeldInputs();lab=createDriveLab(buildCar(owned),readSettings());
  if($('artwork').value!=='factory')lab.vehicle.car.artId=$('artwork').value;
  if(clearTrace){records=[];events=[];sampleClock=0;sampleAccumulator=0;$('event-log').replaceChildren();}
  accumulator=0;lastFeedback='';audio.stop();$('pause').textContent='Pause';$('burnout').textContent='Burnout';$('stage').textContent=lab.settings.staging==='manual'?'Pre-stage':'Stage & start tree';refreshCarUI({ratios:!preserveInputs});updateHUD();drawScene();
}
function clearHeldInputs(){keyboard.clear();pointers.clear();document.querySelectorAll('[data-pedal]').forEach(b=>b.classList.remove('pressed'));}
function releasePedals(){clearHeldInputs();for(const id of ['throttle-input','clutch-input','brake-input'])$(id).value=0;$('latch-throttle').checked=false;$('latch-clutch').checked=false;readInputs();}
function readInputs(){
  const held=pedal=>[...keyboard].some(code=>pedalKeys[code]===pedal)||[...pointers.values()].includes(pedal);
  lab.inputs={throttle:Math.max(Number($('throttle-input').value)/100,held('throttle')||$('latch-throttle').checked?1:0),clutch:Math.max(Number($('clutch-input').value)/100,held('clutch')||$('latch-clutch').checked?1:0),brake:Math.max(Number($('brake-input').value)/100,held('brake')?1:0),blip:held('blip')||performance.now()<blipUntil};
  for(const b of document.querySelectorAll('[data-pedal]'))b.classList.toggle('pressed',lab.inputs[b.dataset.pedal]>0);
}
let blipUntil=0;
function updateHUD(){
  const s=lab.vehicle,c=s.car,t=labTelemetry(lab),put=(id,value)=>{const el=$(id);if(el)el.textContent=value;};
  put('speed',Math.round(t.speed));put('gear',s.gear?(c.transmissionType==='cvt'?'D':s.gear):'N');put('rpm',Math.round(t.rpm).toLocaleString());put('elapsed',t.elapsed.toFixed(3));put('slip',Math.round(t.slip)+'%');put('boost',t.boost.toFixed(2)+' bar');
  $('rpm-fill').style.width=clamp(t.rpm/c.redline*100,0,100)+'%';$('rpm-fill').classList.toggle('optimal',Math.abs(t.rpm-idealShift(c,s.gear || 1))<220);$('shift-marker').style.left=idealShift(c,s.gear || 1)/c.redline*100+'%';put('shift-hint',`${c.transmissionType==='cvt'?'CVT POWER TARGET':'OPTIMAL SHIFT'} ${idealShift(c,s.gear || 1)} RPM`);
  for(const [id,value] of Object.entries({distance:t.distance.toFixed(1)+' m',reaction:t.reaction===null?'—':t.reaction.toFixed(3)+' s','max-speed':t.maxSpeed.toFixed(1)+' km/h',accel:t.acceleration.toFixed(2)+' g','engine-torque':Math.round(t.torque)+' Nm','engine-power':Math.round(t.power)+' HP','tire-temp':t.temperature.toFixed(1)+' °C','tire-wear':t.wear.toFixed(3),'shift-timer':Math.round(s.shiftTimer*1000)+' ms','pedal-throttle':Math.round(t.throttle)+'%','pedal-clutch':Math.round(t.clutch)+'%','pedal-brake':Math.round(t.brake)+'%','engine-stress':t.stress.toFixed(3)}))put(id,value);
  for(const name of ['60ft','eighth','quarter','half','mile'])put('split-'+name,s.splits[name]?s.splits[name].toFixed(3)+' s':'—');
  for(const [id,value,max,text] of [['speed-dial',t.speed,400,Math.round(t.speed)],['rpm-dial',t.rpm/1000,Math.ceil((c.redline+500)/1000),Math.round(t.rpm)],['boost-dial',t.boost,3,t.boost.toFixed(2)]]){$(id+'-needle').setAttribute('transform',`rotate(${-130+clamp(value/max,0,1)*260} 120 120)`);put(id+'-value',text);}
  const phase=lab.paused?'PAUSED':lab.burnout?'BURNOUT':lab.phase.toUpperCase();put('phase-status',phase);put('lab-feedback',lab.feedback);
  $('lab-prestage').classList.toggle('lit',lab.staged);$('lab-stage-light').classList.toggle('lit',lab.phase==='countdown'||lab.phase==='armed'||lab.phase==='running'&&lab.staged);
  for(let i=1;i<=3;i++)document.querySelector(`[data-light="${i}"]`).classList.toggle('lit',lab.phase==='countdown'&&lab.clock>=.65+i*.5);
  document.querySelector('[data-light="green"]').classList.toggle('lit',lab.phase==='armed'||lab.phase==='running'&&lab.staged);document.querySelector('[data-light="red"]').classList.toggle('lit',lab.falseStart);
  for(const el of document.querySelectorAll('input[type=range]')){const out=$(el.id+'-value');if(out)out.textContent=el.value;}
  if(lab.feedback!==lastFeedback){lastFeedback=lab.feedback;addEvent(lab.feedback);}
  audio.update(t.rpm,t.throttle/100,sound&&!lab.paused,.16,{speed:lab.vehicle.v,shifting:lab.vehicle.shiftTimer>0});
}
function sizeCanvas(canvas){const box=canvas.getBoundingClientRect(),dpr=Math.min(2,devicePixelRatio || 1);const w=Math.round(box.width*dpr),h=Math.round(box.height*dpr);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}const ctx=canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);return {ctx,w:box.width,h:box.height};}
function drawScene(){const canvas=$('track-canvas'),{ctx,w,h}=sizeCanvas(canvas);drawTrack(ctx,w,h,{player:lab.vehicle,hideOpponent:true,distance:Infinity,clock:lab.clock,reducedMotion:matchMedia('(prefers-reduced-motion: reduce)').matches,time:$('day').value,weather:$('weather').value,track:TRACKS.find(t=>t.id===$('track').value)});$('track-label').textContent=$('track').selectedOptions[0].textContent.toUpperCase();}
function drawPlot(){
  const {ctx,w,h}=sizeCanvas($('telemetry-plot'));ctx.clearRect(0,0,w,h);ctx.fillStyle='#11151d';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#29313e';ctx.lineWidth=1;for(let i=1;i<5;i++){ctx.beginPath();ctx.moveTo(0,h*i/5);ctx.lineTo(w,h*i/5);ctx.stroke();}
  const points=records.filter(r=>r.time>=sampleClock-60);if(points.length<2)return;
  for(const [key,color,max] of [['speed','#6bd8ee',400],['rpm','#ff9061',lab.vehicle.car.redline+500],['boost','#bd9efa',3],['slip','#ead175',150]]){ctx.strokeStyle=color;ctx.lineWidth=1.5;ctx.beginPath();points.forEach((p,i)=>{const x=w*(p.time-Math.max(0,sampleClock-60))/Math.max(1,Math.min(60,sampleClock)),y=h-10-clamp(p[key]/max,0,1)*(h-20);if(i)ctx.lineTo(x,y);else ctx.moveTo(x,y);});ctx.stroke();}
}
function physicsTick(dt){readInputs();stepDriveLab(lab,dt);if(!lab.paused){sampleClock+=dt;sampleAccumulator+=dt;if(sampleAccumulator>=.1){sampleAccumulator-=.1;records.push({time:sampleClock,...labTelemetry(lab)});if(records.length>6000)records.shift();}}}
function animate(now){const dt=Math.min(.1,(now-(lastFrame || now))/1000);lastFrame=now;if(!lab.paused){accumulator+=dt*Number($('time-scale').value);let steps=0;while(accumulator>=1/120&&steps++<26){physicsTick(1/120);accumulator-=1/120;}}readInputs();updateHUD();drawScene();drawPlot();requestAnimationFrame(animate);}
function pause(){lab.paused=!lab.paused;releasePedals();audio.stop();$('pause').textContent=lab.paused?'Resume':'Pause';accumulator=0;updateHUD();}
function applyBuild(){
  const base=CARS.find(c=>c.id===owned.model);owned.color=$('paint').value;owned.condition=Number($('condition').value);owned.visual={...owned.visual,wheels:$('rim-color').value,finish:$('finish').value,tint:Number($('window-tint').value),stripe:$('stripe').checked,spoiler:$('spoiler').checked,wheelAsset:$('wheel-component').value,brakeAsset:$('brake-component').value,rideHeight:Number($('ride-height').value)};
  owned.upgrades=Object.fromEntries(PARTS.map(p=>[p.id,Number($('part-'+p.id).value)]));
  const ratios=base.ratios.map((r,i)=>Number($('ratio-'+i)?.value || r));
  if(ratios.some((r,i)=>!Number.isFinite(r)||r<.4||r>5.5||i>0&&r>=ratios[i-1])){$('lab-error').textContent='Gear ratios must decrease from first gear to the last, between 0.4 and 5.5.';return;}
  const launchRPM=Number($('launch-rpm').value),shiftRPM=Number($('shift-rpm').value),finalDrive=Number($('final-drive').value);
  if(!Number.isFinite(launchRPM)||launchRPM<900||launchRPM>15000||!Number.isFinite(shiftRPM)||shiftRPM<0||shiftRPM>15000||!Number.isFinite(finalDrive)||finalDrive<2||finalDrive>5.5){$('lab-error').textContent='Enter valid launch RPM, shift RPM and final drive values.';return;}
  owned.tune={launchRPM,shiftRPM,finalDrive,ratios,pressure:Number($('pressure').value),diff:Number($('diff').value),boost:Number($('boost-setting').value)};$('lab-error').textContent='';resetSession({preserveInputs:true});
}
function loadBuild(next){
  owned=structuredClone(next);$('model').value=owned.model;const c=buildCar(owned);
  $('paint').value=c.color;$('condition').value=c.condition;$('ride-height').value=owned.visual?.rideHeight || 0;
  for(const p of PARTS)$('part-'+p.id).value=owned.upgrades?.[p.id] || 0;
  for(const [id,value] of Object.entries({'launch-rpm':c.launchRPM,'shift-rpm':c.shiftRPM,'final-drive':c.finalDrive,pressure:c.pressure,diff:c.diff,'boost-setting':c.boost}))$(id).value=value;
  $('wheel-component').value=owned.visual?.wheelAsset || '';$('brake-component').value=owned.visual?.brakeAsset || '';
  $('rim-color').value=owned.visual?.wheels || 'silver';$('finish').value=owned.visual?.finish || 'metallic';$('window-tint').value=owned.visual?.tint ?? .45;$('stripe').checked=owned.visual?.stripe===true;$('spoiler').checked=owned.visual?.spoiler===true;
  resetSession();
}
function scenario(i){
  releasePedals();resetSession();lab.settings.transmission=i===2?'clutch':'auto';$('transmission').value=lab.settings.transmission;
  if(i===0){lab.vehicle.gear=0;$('throttle-input').value=65;lab.feedback='FREE REV · NEUTRAL';}
  if(i===1){startDriving(lab);$('latch-throttle').checked=true;}
  if(i===2){startDriving(lab);$('latch-throttle').checked=true;$('latch-clutch').checked=true;lab.feedback='CLUTCH TEST · RELEASE CLUTCH TO DRIVE';}
  if(i===3){setLabSpeed(lab,80);$('brake-input').value=100;lab.feedback='BRAKE TEST · 80 KM/H TO STOP';}
  if(i===4){$('weather').value='Wet';$('traction').value=0;$('launch-control').value='auto';lab.settings={...readSettings(),staging:'auto'};stageDriveLab(lab);$('latch-throttle').checked=true;}
  if(i===5){setLabSpeed(lab,80);lab.feedback='ROLLING TEST · APPLY THROTTLE';}
  readInputs();updateHUD();audio.start();
}
function exportData(){const csv=telemetryCSV(records);const url=URL.createObjectURL(new Blob([csv],{type:'text/csv'})),a=document.createElement('a');a.href=url;a.download='redline-test-drive.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);addEvent(`EXPORTED ${records.length} TELEMETRY SAMPLES`);}
shell();
const actions={start:()=>{lab.paused=false;$('pause').textContent='Pause';startDriving(lab);audio.start();},stage:()=>{lab.paused=false;$('pause').textContent='Pause';releasePedals();stageDriveLab(lab);$('stage').textContent=lab.staged?'Stage & start tree':'Pre-stage';audio.start();},launch:()=>{launchDriveLab(lab);audio.start();},burnout:()=>{if(lab.phase==='running')resetSession();lab.burnout=!lab.burnout;$('burnout').textContent=lab.burnout?'Stop burnout':'Burnout';lab.feedback=lab.burnout?'BURNOUT · HOLD THROTTLE':'READY';audio.start();},pause,step:()=>{if(!lab.paused)pause();lab.paused=false;physicsTick(1/120);lab.paused=true;updateHUD();drawScene();drawPlot();},reset:()=>{releasePedals();resetSession();},'shift-up':()=>shiftDriveLab(lab,1),'shift-down':()=>shiftDriveLab(lab,-1),neutral:()=>{lab.vehicle.gear=0;lab.feedback='NEUTRAL';},blip:()=>{blipUntil=performance.now()+250;audio.start();},'apply-speed':()=>setLabSpeed(lab,Number($('prime-speed').value)),'garage-build':()=>{const save=loadSave();loadBuild(save.cars.find(c=>c.uid===save.selected)||save.cars[0]);addEvent('LOADED GARAGE BUILD · READ ONLY');},'factory-build':()=>loadBuild(newCar($('model').value)),'clear-trace':()=>{records=[];events=[];sampleClock=0;sampleAccumulator=0;$('event-log').replaceChildren();},'export-data':exportData};
document.addEventListener('click',e=>{const b=e.target.closest('button[id]');if(!b)return;if(b.id.startsWith('scenario-'))scenario(Number(b.id.slice(9)));else actions[b.id]?.();});
document.addEventListener('pointerdown',e=>{const b=e.target.closest('[data-pedal]');if(!b)return;e.preventDefault();pointers.set(e.pointerId,b.dataset.pedal);b.setPointerCapture(e.pointerId);addEvent(`${b.dataset.pedal.toUpperCase()} PRESSED`);audio.start();readInputs();});
for(const event of ['pointerup','pointercancel','lostpointercapture'])document.addEventListener(event,e=>{const pedal=pointers.get(e.pointerId);if(pedal)addEvent(`${pedal.toUpperCase()} RELEASED`);pointers.delete(e.pointerId);readInputs();});
const pedalKeys={KeyW:'throttle',ArrowUp:'throttle',KeyC:'clutch',KeyS:'brake',ArrowDown:'brake',KeyR:'blip'};
document.addEventListener('keydown',e=>{if(e.target.closest('input,select,textarea,summary'))return;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(pedalKeys[e.code])keyboard.add(e.code);if(e.repeat)return;if(pedalKeys[e.code])addEvent(`${pedalKeys[e.code].toUpperCase()} KEY DOWN`);audio.start();const action={Space:'launch',KeyE:'shift-up',ArrowRight:'shift-up',KeyQ:'shift-down',ArrowLeft:'shift-down',KeyN:'neutral',Escape:'pause'}[e.code];if(action)actions[action]();readInputs();});
document.addEventListener('keyup',e=>{if(keyboard.has(e.code))addEvent(`${pedalKeys[e.code].toUpperCase()} KEY UP`);keyboard.delete(e.code);readInputs();});
document.addEventListener('input',e=>{if(e.target.matches('input[type=range]')){const out=$(e.target.id+'-value');if(out)out.textContent=e.target.value;}if(e.target.id.startsWith('ratio-')||['launch-rpm','shift-rpm','final-drive'].includes(e.target.id))applyBuild();});
document.addEventListener('change',e=>{
  const id=e.target.id;if(id==='model'){loadBuild(newCar(e.target.value));return;}
  if(id==='difficulty'){const d=DIFFICULTIES[e.target.value];$('transmission').value=d.transmission;$('launch-control').value=d.launch;$('traction').value=d.traction*100;lab.settings=readSettings();return;}
  if(id==='sound'){sound=e.target.checked;audio.start();return;}
  if(['transmission','launch-control','staging','traction','rev-match','track','weather','day'].includes(id)){lab.settings=readSettings();$('stage').textContent=lab.settings.staging==='manual'&&!lab.staged?'Pre-stage':'Stage & start tree';return;}
  if(['throttle-input','clutch-input','brake-input','time-scale','latch-throttle','latch-clutch'].includes(id)){readInputs();audio.start();return;}
  if(id==='artwork'){resetSession();return;}
  if(id.startsWith('part-')||id.startsWith('ratio-')||['paint','condition','ride-height','rim-color','finish','window-tint','stripe','spoiler','wheel-component','brake-component','launch-rpm','shift-rpm','final-drive','pressure','diff','boost-setting'].includes(id))applyBuild();
});
window.addEventListener('blur',()=>{clearHeldInputs();if(!lab.paused)pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&!lab.paused)pause();});
window.addEventListener('beforeunload',()=>audio.stop());
try{const response=await fetch(new URL('./assets/cars/manifest.json',import.meta.url));if(!response.ok)throw Error(`Manifest HTTP ${response.status}`);const production=await response.json();pack={schemaVersion:1,cars:{...demoSpritePack.cars,...production.cars},components:{wheels:{...demoSpritePack.components.wheels,...production.components?.wheels},brakes:{...demoSpritePack.components.brakes,...production.components?.brakes}}};await installSpritePack(pack,new URL('./assets/cars/',import.meta.url));
  options('artwork',[['factory','Model artwork'],...Object.keys(pack.cars).map(id=>[id,id==='layer-demo'?'Layer geometry demo':id])]);options('wheel-component',[['','Factory'],...componentOptions('wheels')]);options('brake-component',[['','Factory'],...componentOptions('brakes')]);$('lab-asset-status').textContent=`${Object.keys(production.cars || {}).length} production car packs loaded, plus the isolated geometry demo.`;refreshCarUI();
}catch(error){$('lab-error').textContent=error.message;$('lab-asset-status').textContent='Using vector model artwork.';}
requestAnimationFrame(animate);
