import { factoryTemplate } from './vehicle-details.js';
import { CARS, EVENTS, BUSINESS_RATES, DISTANCES } from './data.js';
import { buildCar, rating } from './physics.js';
import { isBusy } from './storage.js';
import { carSVG } from './graphics.js';
import { money, escape, icon } from './views.js';

const button=(label,action,kind='secondary',attrs='')=>`<button class="button ${kind}" data-action="${action}" ${attrs}>${label}</button>`;
const dialogButton=(label,id)=>`<button class="button secondary" data-dialog="${id}">${label}</button>`;

export function shell(s,page,content){
  const nav=[['garage','Garage','My garage'],['race','Race','Free race'],['career','Career','Career'],['tuning','Workshop','Upgrade & tune'],['dealership','Car lot','Dealership'],['business','The shop','Garage business']];
  const level=Math.floor(s.xp/250)+1;
  return `<div class="game-shell" data-screen="${page}"><header class="game-topbar"><a class="game-brand" href="#garage" aria-label="Redline garage"><b>R<span>//</span></b><div>REDLINE<small>DRAG CLUB</small></div></a><div class="driver-hud"><span class="driver-number">07</span><div><strong>INDEPENDENT RACER</strong><small>LVL ${level} <span class="driver-xp"><i style="width:${s.xp%250/2.5}%"></i></span></small></div></div><div class="balances"><div class="cash-balance"><small>CREDITS</small><strong id="balance">${money(s.cash)}</strong></div><div class="rep-balance">${icon('bolt')}<span>${s.rep.toLocaleString()} <small>REP</small></span></div><span class="saved" id="save-status"><i></i> SAVED</span><button class="top-settings" data-nav="settings" aria-label="Settings & controls">${icon('settings')}</button><button class="top-settings fullscreen-button" data-fullscreen aria-label="Toggle fullscreen">⛶</button></div></header><main id="main" class="game-main" tabindex="-1">${content}</main><div class="game-bottom"><span class="menu-hint">SELECT YOUR NEXT MOVE</span><nav class="game-nav" aria-label="Game menu">${nav.map(([id,label,aria],i)=>`<button class="game-nav-item ${page===id?'active':''}" data-nav="${id}" aria-label="${aria}" ${page===id?'aria-current="page"':''}><span class="nav-index">0${i+1}</span>${icon(id)}<span>${label}</span></button>`).join('')}</nav><span class="menu-hint right">REDLINE / CLUB 07</span></div></div><div id="dialog-host"></div>`;
}

export function garage(s){
  const o=s.cars.find(c=>c.uid===s.selected)||s.cars[0],c=buildCar(o),r=rating(c),busy=isBusy(s,o.uid),record=s.records[`${o.uid}-402.336`];
  const next=EVENTS.find(e=>!s.completed.includes(e.id));
  return `<section class="garage-screen"><div class="garage-scene" id="garage-scene" aria-hidden="true"></div><div class="garage-fallback" aria-hidden="true">${carSVG(c)}</div><div class="garage-vignette"></div><div class="garage-heading"><span class="eyebrow">HOME BASE / BAY 07</span><h1>THE GARAGE<span>YOUR CAR. YOUR RULES.</span></h1></div><div class="garage-status"><i></i>${busy?'ON A CUSTOMER JOB':'READY TO RACE'}<small>${Math.round(c.condition)}% CONDITION</small></div><div class="garage-car-info"><span class="class-badge">${r.tier}</span><div><span class="eyebrow">${escape(c.subtitle)} / ${r.pp} PP</span><h2>${escape(c.name)}</h2><p>${escape(c.engine)} <span>·</span> ${c.drivetrainLabel||c.drive} <span>·</span> ${c.transmissionType==='cvt'?'CVT':c.ratios.length+'-SPEED'}</p></div></div><div class="garage-telemetry">${[[c.hp,'HORSEPOWER','HP'],[c.peakTorque,'TORQUE','Nm'],[r.et.toFixed(2),'EST. ¼ MILE','SEC'],[record?record.toFixed(3):'—','BEST PASS','SEC']].map(([v,label,unit])=>`<div><span>${label}</span><strong>${v}<small>${unit}</small></strong></div>`).join('')}</div><div class="garage-actions"><div class="garage-tools">${dialogButton(`Collection <b>${s.cars.length.toString().padStart(2,'0')}</b>`,'collection')}${dialogButton('Build details','build')}${dialogButton('Run history','history')}<button class="button secondary" data-nav="tuning">${icon('tuning')} Workshop</button></div><button class="button primary race-cta" data-action="race-now" ${busy?'disabled':''}><span>HIT THE STRIP<small>FREE RUN / ${DISTANCES.find(d=>d.value===s.free.distance)?.name||'¼ mile'}</small></span>${icon('arrow')}</button></div><div class="garage-mission"><span class="eyebrow">NEXT CAREER EVENT</span><strong>${escape(next?.name||'Club champion')}</strong><button class="text-button" data-nav="career">${s.completed.length} / 28 WON ${icon('arrow')}</button></div></section>
  <template id="collection"><div class="collection-grid dialog-grid">${s.cars.map(car=>{const b=buildCar(car),rr=rating(b);return `<button class="collection-card ${car.uid===o.uid?'selected':''}" data-action="select-car" data-id="${car.uid}"><div class="collection-label"><span class="tag class-tag">${rr.tier}</span>${car.uid===o.uid?'<span class="selected-label">SELECTED</span>':isBusy(s,car.uid)?'<span class="tag">ON A JOB</span>':''}</div>${carSVG(b)}<div><strong>${escape(b.name)}</strong><span>${b.hp} HP · ${b.drive} · ${rr.pp} PP</span></div></button>`;}).join('')}<button class="collection-card add-car" data-nav="dealership"><span>+</span><strong>Find your next car</strong><small>Visit the car lot</small></button></div></template>
  <template id="build"><div class="build-modal"><div class="build-modal-art">${carSVG(c)}</div><h2>${escape(c.name)}</h2><div class="technical-grid">${Object.entries({'Engine':c.engine,'Drivetrain':c.drive,'Mass':`${Math.round(c.mass)} kg`,'Power':`${c.hp} HP`,'Torque':`${c.peakTorque} Nm`,'Performance':`${r.tier} / ${r.pp} PP`,'0–60 mph':`${r.zero60.toFixed(2)} sec`,'¼ mile estimate':`${r.et.toFixed(2)} sec`,'Condition':`${Math.round(c.condition)}%`}).map(([k,v])=>`<div><span>${k}</span><strong>${escape(v)}</strong></div>`).join('')}</div>${c.manufacturerReference?`<button class="button secondary" data-dialog="factory-${c.id}">Factory specs & sources</button>`:''}<button class="button primary" data-nav="tuning">Open workshop ${icon('arrow')}</button></div></template>
  ${factoryTemplate(c)}<template id="history"><div class="history-grid">${s.history.length?s.history.map(h=>`<div class="run-row"><span class="tag ${h.won?'green':''}">${h.won?'WIN':'LOSS'}</span><strong>${escape(h.name)}</strong><span>${h.et.toFixed(3)} sec</span><span>${Math.round(h.trap)} km/h</span></div>`).join(''):`<div class="empty-state"><b>YOUR FIRST SLIP IS WAITING.</b><p>Complete a pass to record your time here.</p>${button('Hit the strip','race-now','primary')}</div>`}</div></template>`;
}

export function resultView(result,r,s){
  const invalid=result.falseStart||result.dnf,p=r.player,o=r.opponent;
  const time=v=>Number.isFinite(v)?v.toFixed(3):'—';
  const rows=[['REACTION',invalid?'—':time(p.reaction),time(o.started?o.reaction:null)],['60 FT',time(p.splits['60ft']),time(o.splits['60ft'])],['⅛ MILE',time(p.splits.eighth),time(o.splits.eighth)],['¼ MILE',time(p.splits.quarter),time(o.splits.quarter)]];
  if(r.distance>=804.672)rows.push(['½ MILE',time(p.splits.half),time(o.splits.half)]);
  if(r.distance>=1609.344)rows.push(['1 MILE',time(p.splits.mile),time(o.splits.mile)]);
  rows.push(['ELAPSED TIME',invalid?'—':time(p.finishTime),time(o.finishTime)],['TRAP / KM/H',invalid?'—':p.trap.toFixed(1),o.finished?o.trap.toFixed(1):'—'],['TOTAL + RT',invalid?'—':time(p.finishTime+p.reaction),o.finished?time(o.finishTime+o.reaction):'—']);
  const outcome=result.falseStart?'RED LIGHT':result.dnf?'NO TIME':result.won?'WINNER':'RUNNER UP';
  return `<div class="results-backdrop"><section class="result-panel slip-result" role="dialog" aria-modal="true" aria-labelledby="result-title"><div class="slip-printer"><span>REDLINE TIMING SYSTEM</span><i></i></div><article class="timing-slip"><header class="slip-header"><b>REDLINE DRAG CLUB</b><span>${escape(r.track.name.toUpperCase())}</span><small>${DISTANCES.find(d=>d.value===r.distance)?.name||Math.round(r.distance)+' M'} / ${r.weather.toUpperCase()} / ${r.time.toUpperCase()}</small><small>RUN ${String(s.history.length||1).padStart(4,'0')} · ${new Date().toLocaleDateString('en-CA')}</small></header><h1 id="result-title" tabindex="-1">${result.falseStart?'Red light.':result.dnf?'No clean pass.':result.won?'That’s your lane.':'So close. Go again.'}</h1><div class="slip-verdict ${result.won?'won':''}">${outcome}${result.personalBest?'<span>★ PERSONAL BEST</span>':''}</div><div class="slip-lanes"><span>TIME / SEC</span><strong>LEFT / YOU</strong><strong>RIGHT / RIVAL</strong></div><div class="slip-cars"><span></span><span>${escape(p.car.name)}</span><span>${escape(o.car.name)}</span></div><div class="slip-rows">${rows.map(([label,left,right],i)=>`<div class="slip-row ${label==='ELAPSED TIME'?'slip-et':''}" style="--row:${i}"><span>${label}</span><strong>${left}</strong><strong>${right}</strong></div>`).join('')}</div><p class="slip-note">${result.falseStart?'DISQUALIFIED: LEFT BEFORE GREEN.':result.dnf?'RUN TIMED OUT. CHECK THROTTLE, CLUTCH AND GEARING.':'WINNER DETERMINED BY ELAPSED TIME + REACTION.'}</p><div class="slip-rewards"><span>CREDITS <b>+${money(result.cash)}</b></span><span>REP <b>+${result.rep}</b></span><span>XP <b>+${result.xp}</b></span></div>${result.prize?`<div class="slip-prize">PRIZE CAR: ${escape(result.prize)}</div>`:''}<div class="slip-barcode" aria-hidden="true"></div><span class="slip-footer">KEEP IT CLEAN. KEEP IT QUICK.</span></article><div class="slip-actions">${button('Run it back','retry','primary')}${button('Back to garage','finish-garage')}${r.event?button('Continue career','finish-career'):''}</div></section></div>`;
}
